# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-20 14:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to=b'')),
                ('category', models.CharField(choices=[('vd', 'Vajra Dance'), ('khaita', 'Khaita'), ('medicine', 'Tibetan Medicine'), ('yy', 'Yantra Yoga'), ('art', 'Visual Art'), ('vd', 'Vajra Dance'), ('inner', 'Inner Knowledge')], max_length=20)),
                ('metadata', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_entries', to='authors.Author')),
            ],
        ),
    ]
