# Generated by Django 2.0.2 on 2018-03-02 13:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0007_auto_20180228_1038'),
        ('entries', '0003_auto_20180302_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='competition',
            field=models.ForeignKey(default=1, on_delete=False, related_name='related_entries', to='competition.Competition'),
            preserve_default=False,
        ),
    ]
