# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-20 14:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField()),
                ('summary', models.TextField()),
                ('description', models.TextField()),
                ('terms_conditions', models.TextField()),
                ('start', models.DateField()),
                ('finish', models.DateField()),
                ('final', models.DateField()),
                ('jury', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Prize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True, null=True)),
                ('observations', models.TextField(blank=True, null=True)),
                ('aworded', models.ManyToManyField(blank=True, related_name='related_awords', to='authors.Author')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_prizes', to='competition.Competition')),
            ],
        ),
    ]
