# Generated by Django 2.0.2 on 2018-02-21 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prize',
            name='aworded',
            field=models.ManyToManyField(blank=True, related_name='related_awords', to='entries.Entry'),
        ),
        migrations.AlterField(
            model_name='prize',
            name='competition',
            field=models.ForeignKey(on_delete=False, related_name='related_prizes', to='competition.Competition'),
        ),
    ]
