# Generated by Django 2.0.2 on 2018-02-22 16:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0002_auto_20180221_0852'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='competition',
            name='organizer',
            field=models.CharField(default=django.utils.timezone.now, max_length=250),
            preserve_default=False,
        ),
    ]
