# Generated by Django 2.0.2 on 2018-02-22 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0003_auto_20180222_1607'),
    ]

    operations = [
        migrations.RenameField(
            model_name='competition',
            old_name='final',
            new_name='finals',
        ),
    ]
