# Generated by Django 2.0.2 on 2018-02-22 17:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0004_auto_20180222_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='categories',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
