# Generated by Django 2.0.2 on 2018-02-26 11:46

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0005_competition_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='competition',
            name='jury',
            field=models.ManyToManyField(related_name='related_judges', to=settings.AUTH_USER_MODEL),
        ),
    ]
