# Generated by Django 2.0.2 on 2018-02-28 10:38

from django.conf import settings
from django.db import migrations, models
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('competition', '0006_auto_20180226_1146'),
    ]

    operations = [
        migrations.CreateModel(
            name='Juror',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=250)),
            ],
        ),
        migrations.RemoveField(
            model_name='competition',
            name='jury',
        ),
        migrations.AlterField(
            model_name='competition',
            name='description',
            field=djrichtextfield.models.RichTextField(),
        ),
        migrations.AlterField(
            model_name='competition',
            name='terms_conditions',
            field=djrichtextfield.models.RichTextField(),
        ),
        migrations.AddField(
            model_name='juror',
            name='competition',
            field=models.ForeignKey(on_delete=False, related_name='jurors', to='competition.Competition'),
        ),
        migrations.AddField(
            model_name='juror',
            name='user',
            field=models.ForeignKey(on_delete=False, related_name='related_jurors', to=settings.AUTH_USER_MODEL),
        ),
    ]
